services:
  jenkins:
    container_name: jenkins
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - "8010:8080"  # Jenkins UI
      - "50000:50000"  # Jenkins agent communication
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Allows Jenkins to use Docker commands
      - ./init.groovy.d:/usr/share/jenkins/ref/init.groovy.d
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false  # Skip initial setup wizard

volumes:
  jenkins_home:
    driver: local